services:
  db:
    image: mariadb:10.9
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-nordeidevågen}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-forening}
      MYSQL_USER: ${MYSQL_USER:-forening}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-nordeidevågen}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  noco:
    image: nocodb/nocodb:latest
    ports:
      - "8080:8080"
    environment:
      # Enkel URL i stedet for NC_DB_*-feltene
      NC_DB_URL: mysql://${MYSQL_USER:-forening}:${MYSQL_PASSWORD:-nordeidevågen}@db:3306/${MYSQL_DATABASE:-forening}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - noco_data:/usr/app/data

  app:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - noco

  invoicer:
    build: ./invoicer
    restart: "no"
    depends_on:
      - noco

volumes:
  db_data:
  noco_data:
